version: "3"
services:
  springboot:
    container_name: runner-api
    image: duckbill413/runner-docker-api:latest # {{docker-hub-name}}/{{image-name}}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      TZ: "Asia/Seoul"
    networks:
      - runner-net
    volumes:
      - /home/ec2-user/logs:/logs

  redis:
    image: redis:alpine
    container_name: runner-redis
    command: redis-server --port 6379
    hostname: redis
    ports:
      - "6800:6379"
    networks:
      - runner-net
    restart: always

  nginx:
    container_name: runner-nginx
    image: duckbill413/runner-docker-nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro # letsencrypt 인증키의 경로
    ports:
      - "80:80"
      - "443:443"
    networks:
      - runner-net
    depends_on:
      - springboot

networks:
  runner-net:
    driver: bridge